# Generated by Django 3.1.7 on 2021-03-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_tb',
        ),
    ]
