# Generated by Django 3.1.7 on 2021-03-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_category_tb'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.category_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller_tb')),
            ],
        ),
    ]
