# Generated by Django 3.1.7 on 2021-03-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_image_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_tb',
            name='category',
        ),
    ]
