# Generated by Django 3.1.7 on 2021-04-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_order_tb'),
        ('Seller', '0003_remove_image_tb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='track_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingdetails', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.order_tb')),
            ],
        ),
    ]
