# Generated by Django 3.1.7 on 2021-03-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_remove_image_tb_category'),
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.image_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller_tb')),
            ],
        ),
    ]
