# Generated by Django 3.1.7 on 2021-03-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20210324_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_tb',
            name='buyer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Buyer.register_tb'),
        ),
    ]
