# Generated by Django 3.1.7 on 2021-03-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart_tb_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_tb',
            old_name='name',
            new_name='number',
        ),
    ]
