# Generated by Django 3.1.7 on 2021-03-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_remove_image_tb_category'),
        ('Buyer', '0005_auto_20210324_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('buyer_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Buyer.register_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.image_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller_tb')),
            ],
        ),
    ]
